const QUESTIONTYPE = {
    TRUEORFALSE: "TRUEORFALSE",
    CHOICEONE: "CHOICEONE",
    MULTIPLECHOICE: "MULTIPLECHOICE",
    FILLINTHEBLANK : "FILLINTHEBLANK",
    ORDERING : "ORDERING",
};
  
module.exports = QUESTIONTYPE;
  