const QUESTIONTYPE = {
  TRUEORFALSE: "TRUEORFALSE",
  CHOICEONE: "CHOICEONE",
  MULTIPLECHOICE: "MULTIPLECHOICE",
  FILLINTHEBLANK: "FILLINTHEBLANK",
  ORDERING: "ORDERING",

  getType: (type) => {
    switch (type) {
      case QUESTIONTYPE.TRUEORFALSE:
        return QUESTIONTYPE.TRUEORFALSE;
      case QUESTIONTYPE.CHOICEONE:
        return QUESTIONTYPE.CHOICEONE;
      case QUESTIONTYPE.MULTIPLECHOICE:
        return QUESTIONTYPE.MULTIPLECHOICE;
      case QUESTIONTYPE.FILLINTHEBLANK:
        return QUESTIONTYPE.FILLINTHEBLANK;
      case QUESTIONTYPE.ORDERING:
        return QUESTIONTYPE.ORDERING;
     
      default:
        throw Error('Type not supported!')
    }
  },
};

module.exports = QUESTIONTYPE;
