const QUIZCATEGORY = {
  ALLGEMEIN: "ALLGEMEIN",
  MATH: "MATH",
  SPORT: "SPORT",
  TEST: "TEST",
  TEST1 :"TEST1",
  TEST2: "TEST2",
  TEST3: "TEST3",
  TEST4: "TEST4",

};

module.exports = QUIZCATEGORY;
