// TODO: fetch from Server

const QUESTIONTYPE = {
  TRUEORFALSE: "TRUEORFALSE",
  CHOICEONE: "CHOICEONE",
  MULTIPLECHOICE: "MULTIPLECHOICE",
  FILLINTHEBLANK: "FILLINTHEBLANK",

  getType: (type) => {
    switch (type) {
      case QUESTIONTYPE.TRUEORFALSE:
        return QUESTIONTYPE.TRUEORFALSE;
      case QUESTIONTYPE.CHOICEONE:
        return QUESTIONTYPE.CHOICEONE;
      case QUESTIONTYPE.MULTIPLECHOICE:
        return QUESTIONTYPE.MULTIPLECHOICE;
      case QUESTIONTYPE.FILLINTHEBLANK:
        return QUESTIONTYPE.FILLINTHEBLANK;

      default:
        alert("false Type")
    }
  },
};





export const QUESTIONTYPE_ARRAY = ["TRUEORFALSE",
  "CHOICEONE",
  "MULTIPLECHOICE",
  "FILLINTHEBLANK",
  "ORDERING",]



export default QUESTIONTYPE;