name: Count Lines of Code

on:
  push:
    branches:
      - main  # Ändere dies auf den Namen deiner Standard-Branch

jobs:
  count-loc:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Count lines of code
      run: |
        git clone https://github.com/AlDanial/cloc.git
        cd cloc
        perl cloc /github/workspace
